apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  {{- if (eq (.Values.service.type) "LoadBalancer") }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- range $f := .Values.service.externalIPs }}
    - {{ $f }}
    {{- end }}
  {{- end }}
  {{- end }}
  selector:
    app: vcluster
    release: {{ .Release.Name }}
